// ///////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) Logan Barnes - All Rights Reserved
// ///////////////////////////////////////////////////////////////////////////////////////
#include "ltb/wgpu/enum_strings.hpp"

namespace ltb::wgpu
{

auto to_string( WGPUFeatureName const feature ) -> std::string_view
{
    switch ( feature )
    {
        case WGPUFeatureName_CoreFeaturesAndLimits:
            return "WGPUFeatureName_CoreFeaturesAndLimits";
        case WGPUFeatureName_DepthClipControl:
            return "WGPUFeatureName_DepthClipControl";
        case WGPUFeatureName_Depth32FloatStencil8:
            return "WGPUFeatureName_Depth32FloatStencil8";
        case WGPUFeatureName_TextureCompressionBC:
            return "WGPUFeatureName_TextureCompressionBC";
        case WGPUFeatureName_TextureCompressionBCSliced3D:
            return "WGPUFeatureName_TextureCompressionBCSliced3D";
        case WGPUFeatureName_TextureCompressionETC2:
            return "WGPUFeatureName_TextureCompressionETC2";
        case WGPUFeatureName_TextureCompressionASTC:
            return "WGPUFeatureName_TextureCompressionASTC";
        case WGPUFeatureName_TextureCompressionASTCSliced3D:
            return "WGPUFeatureName_TextureCompressionASTCSliced3D";
        case WGPUFeatureName_TimestampQuery:
            return "WGPUFeatureName_TimestampQuery";
        case WGPUFeatureName_IndirectFirstInstance:
            return "WGPUFeatureName_IndirectFirstInstance";
        case WGPUFeatureName_ShaderF16:
            return "WGPUFeatureName_ShaderF16";
        case WGPUFeatureName_RG11B10UfloatRenderable:
            return "WGPUFeatureName_RG11B10UfloatRenderable";
        case WGPUFeatureName_BGRA8UnormStorage:
            return "WGPUFeatureName_BGRA8UnormStorage";
        case WGPUFeatureName_Float32Filterable:
            return "WGPUFeatureName_Float32Filterable";
        case WGPUFeatureName_Float32Blendable:
            return "WGPUFeatureName_Float32Blendable";
        case WGPUFeatureName_ClipDistances:
            return "WGPUFeatureName_ClipDistances";
        case WGPUFeatureName_DualSourceBlending:
            return "WGPUFeatureName_DualSourceBlending";
        case WGPUFeatureName_Subgroups:
            return "WGPUFeatureName_Subgroups";
        case WGPUFeatureName_TextureFormatsTier1:
            return "WGPUFeatureName_TextureFormatsTier1";
        case WGPUFeatureName_TextureFormatsTier2:
            return "WGPUFeatureName_TextureFormatsTier2";
        case WGPUFeatureName_PrimitiveIndex:
            return "WGPUFeatureName_PrimitiveIndex";
        case WGPUFeatureName_DawnInternalUsages:
            return "WGPUFeatureName_DawnInternalUsages";
        case WGPUFeatureName_DawnMultiPlanarFormats:
            return "WGPUFeatureName_DawnMultiPlanarFormats";
        case WGPUFeatureName_DawnNative:
            return "WGPUFeatureName_DawnNative";
        case WGPUFeatureName_ChromiumExperimentalTimestampQueryInsidePasses:
            return "WGPUFeatureName_ChromiumExperimentalTimestampQueryInsidePasses";
        case WGPUFeatureName_ImplicitDeviceSynchronization:
            return "WGPUFeatureName_ImplicitDeviceSynchronization";
        case WGPUFeatureName_TransientAttachments:
            return "WGPUFeatureName_TransientAttachments";
        case WGPUFeatureName_MSAARenderToSingleSampled:
            return "WGPUFeatureName_MSAARenderToSingleSampled";
        case WGPUFeatureName_D3D11MultithreadProtected:
            return "WGPUFeatureName_D3D11MultithreadProtected";
        case WGPUFeatureName_ANGLETextureSharing:
            return "WGPUFeatureName_ANGLETextureSharing";
        case WGPUFeatureName_PixelLocalStorageCoherent:
            return "WGPUFeatureName_PixelLocalStorageCoherent";
        case WGPUFeatureName_PixelLocalStorageNonCoherent:
            return "WGPUFeatureName_PixelLocalStorageNonCoherent";
        case WGPUFeatureName_Unorm16TextureFormats:
            return "WGPUFeatureName_Unorm16TextureFormats";
        case WGPUFeatureName_Snorm16TextureFormats:
            return "WGPUFeatureName_Snorm16TextureFormats";
        case WGPUFeatureName_MultiPlanarFormatExtendedUsages:
            return "WGPUFeatureName_MultiPlanarFormatExtendedUsages";
        case WGPUFeatureName_MultiPlanarFormatP010:
            return "WGPUFeatureName_MultiPlanarFormatP010";
        case WGPUFeatureName_HostMappedPointer:
            return "WGPUFeatureName_HostMappedPointer";
        case WGPUFeatureName_MultiPlanarRenderTargets:
            return "WGPUFeatureName_MultiPlanarRenderTargets";
        case WGPUFeatureName_MultiPlanarFormatNv12a:
            return "WGPUFeatureName_MultiPlanarFormatNv12a";
        case WGPUFeatureName_FramebufferFetch:
            return "WGPUFeatureName_FramebufferFetch";
        case WGPUFeatureName_BufferMapExtendedUsages:
            return "WGPUFeatureName_BufferMapExtendedUsages";
        case WGPUFeatureName_AdapterPropertiesMemoryHeaps:
            return "WGPUFeatureName_AdapterPropertiesMemoryHeaps";
        case WGPUFeatureName_AdapterPropertiesD3D:
            return "WGPUFeatureName_AdapterPropertiesD3D";
        case WGPUFeatureName_AdapterPropertiesVk:
            return "WGPUFeatureName_AdapterPropertiesVk";
        case WGPUFeatureName_R8UnormStorage:
            return "WGPUFeatureName_R8UnormStorage";
        case WGPUFeatureName_DawnFormatCapabilities:
            return "WGPUFeatureName_DawnFormatCapabilities";
        case WGPUFeatureName_DawnDrmFormatCapabilities:
            return "WGPUFeatureName_DawnDrmFormatCapabilities";
        case WGPUFeatureName_Norm16TextureFormats:
            return "WGPUFeatureName_Norm16TextureFormats";
        case WGPUFeatureName_MultiPlanarFormatNv16:
            return "WGPUFeatureName_MultiPlanarFormatNv16";
        case WGPUFeatureName_MultiPlanarFormatNv24:
            return "WGPUFeatureName_MultiPlanarFormatNv24";
        case WGPUFeatureName_MultiPlanarFormatP210:
            return "WGPUFeatureName_MultiPlanarFormatP210";
        case WGPUFeatureName_MultiPlanarFormatP410:
            return "WGPUFeatureName_MultiPlanarFormatP410";
        case WGPUFeatureName_SharedTextureMemoryVkDedicatedAllocation:
            return "WGPUFeatureName_SharedTextureMemoryVkDedicatedAllocation";
        case WGPUFeatureName_SharedTextureMemoryAHardwareBuffer:
            return "WGPUFeatureName_SharedTextureMemoryAHardwareBuffer";
        case WGPUFeatureName_SharedTextureMemoryDmaBuf:
            return "WGPUFeatureName_SharedTextureMemoryDmaBuf";
        case WGPUFeatureName_SharedTextureMemoryOpaqueFD:
            return "WGPUFeatureName_SharedTextureMemoryOpaqueFD";
        case WGPUFeatureName_SharedTextureMemoryZirconHandle:
            return "WGPUFeatureName_SharedTextureMemoryZirconHandle";
        case WGPUFeatureName_SharedTextureMemoryDXGISharedHandle:
            return "WGPUFeatureName_SharedTextureMemoryDXGISharedHandle";
        case WGPUFeatureName_SharedTextureMemoryD3D11Texture2D:
            return "WGPUFeatureName_SharedTextureMemoryD3D11Texture2D";
        case WGPUFeatureName_SharedTextureMemoryIOSurface:
            return "WGPUFeatureName_SharedTextureMemoryIOSurface";
        case WGPUFeatureName_SharedTextureMemoryEGLImage:
            return "WGPUFeatureName_SharedTextureMemoryEGLImage";
        case WGPUFeatureName_SharedFenceVkSemaphoreOpaqueFD:
            return "WGPUFeatureName_SharedFenceVkSemaphoreOpaqueFD";
        case WGPUFeatureName_SharedFenceSyncFD:
            return "WGPUFeatureName_SharedFenceSyncFD";
        case WGPUFeatureName_SharedFenceVkSemaphoreZirconHandle:
            return "WGPUFeatureName_SharedFenceVkSemaphoreZirconHandle";
        case WGPUFeatureName_SharedFenceDXGISharedHandle:
            return "WGPUFeatureName_SharedFenceDXGISharedHandle";
        case WGPUFeatureName_SharedFenceMTLSharedEvent:
            return "WGPUFeatureName_SharedFenceMTLSharedEvent";
        case WGPUFeatureName_SharedBufferMemoryD3D12Resource:
            return "WGPUFeatureName_SharedBufferMemoryD3D12Resource";
        case WGPUFeatureName_StaticSamplers:
            return "WGPUFeatureName_StaticSamplers";
        case WGPUFeatureName_YCbCrVulkanSamplers:
            return "WGPUFeatureName_YCbCrVulkanSamplers";
        case WGPUFeatureName_ShaderModuleCompilationOptions:
            return "WGPUFeatureName_ShaderModuleCompilationOptions";
        case WGPUFeatureName_DawnLoadResolveTexture:
            return "WGPUFeatureName_DawnLoadResolveTexture";
        case WGPUFeatureName_DawnPartialLoadResolveTexture:
            return "WGPUFeatureName_DawnPartialLoadResolveTexture";
        case WGPUFeatureName_MultiDrawIndirect:
            return "WGPUFeatureName_MultiDrawIndirect";
        case WGPUFeatureName_DawnTexelCopyBufferRowAlignment:
            return "WGPUFeatureName_DawnTexelCopyBufferRowAlignment";
        case WGPUFeatureName_FlexibleTextureViews:
            return "WGPUFeatureName_FlexibleTextureViews";
        case WGPUFeatureName_ChromiumExperimentalSubgroupMatrix:
            return "WGPUFeatureName_ChromiumExperimentalSubgroupMatrix";
        case WGPUFeatureName_SharedFenceEGLSync:
            return "WGPUFeatureName_SharedFenceEGLSync";
        case WGPUFeatureName_DawnDeviceAllocatorControl:
            return "WGPUFeatureName_DawnDeviceAllocatorControl";
        case WGPUFeatureName_TextureComponentSwizzle:
            return "WGPUFeatureName_TextureComponentSwizzle";
        case WGPUFeatureName_ChromiumExperimentalBindless:
            return "WGPUFeatureName_ChromiumExperimentalBindless";
        case WGPUFeatureName_AdapterPropertiesWGPU:
            return "WGPUFeatureName_AdapterPropertiesWGPU";
        case WGPUFeatureName_Force32:
            return "WGPUFeatureName_Force32";
    }
    return "Unknown WGPUFeatureName";
}

auto to_string( WGPUTextureFormat const format ) -> std::string_view
{
    switch ( format )
    {
        case WGPUTextureFormat_Undefined:
            return "WGPUTextureFormat_Undefined";
        case WGPUTextureFormat_R8Unorm:
            return "WGPUTextureFormat_R8Unorm";
        case WGPUTextureFormat_R8Snorm:
            return "WGPUTextureFormat_R8Snorm";
        case WGPUTextureFormat_R8Uint:
            return "WGPUTextureFormat_R8Uint";
        case WGPUTextureFormat_R8Sint:
            return "WGPUTextureFormat_R8Sint";
        case WGPUTextureFormat_R16Unorm:
            return "WGPUTextureFormat_R16Unorm";
        case WGPUTextureFormat_R16Snorm:
            return "WGPUTextureFormat_R16Snorm";
        case WGPUTextureFormat_R16Uint:
            return "WGPUTextureFormat_R16Uint";
        case WGPUTextureFormat_R16Sint:
            return "WGPUTextureFormat_R16Sint";
        case WGPUTextureFormat_R16Float:
            return "WGPUTextureFormat_R16Float";
        case WGPUTextureFormat_RG8Unorm:
            return "WGPUTextureFormat_RG8Unorm";
        case WGPUTextureFormat_RG8Snorm:
            return "WGPUTextureFormat_RG8Snorm";
        case WGPUTextureFormat_RG8Uint:
            return "WGPUTextureFormat_RG8Uint";
        case WGPUTextureFormat_RG8Sint:
            return "WGPUTextureFormat_RG8Sint";
        case WGPUTextureFormat_R32Float:
            return "WGPUTextureFormat_R32Float";
        case WGPUTextureFormat_R32Uint:
            return "WGPUTextureFormat_R32Uint";
        case WGPUTextureFormat_R32Sint:
            return "WGPUTextureFormat_R32Sint";
        case WGPUTextureFormat_RG16Unorm:
            return "WGPUTextureFormat_RG16Unorm";
        case WGPUTextureFormat_RG16Snorm:
            return "WGPUTextureFormat_RG16Snorm";
        case WGPUTextureFormat_RG16Uint:
            return "WGPUTextureFormat_RG16Uint";
        case WGPUTextureFormat_RG16Sint:
            return "WGPUTextureFormat_RG16Sint";
        case WGPUTextureFormat_RG16Float:
            return "WGPUTextureFormat_RG16Float";
        case WGPUTextureFormat_RGBA8Unorm:
            return "WGPUTextureFormat_RGBA8Unorm";
        case WGPUTextureFormat_RGBA8UnormSrgb:
            return "WGPUTextureFormat_RGBA8UnormSrgb";
        case WGPUTextureFormat_RGBA8Snorm:
            return "WGPUTextureFormat_RGBA8Snorm";
        case WGPUTextureFormat_RGBA8Uint:
            return "WGPUTextureFormat_RGBA8Uint";
        case WGPUTextureFormat_RGBA8Sint:
            return "WGPUTextureFormat_RGBA8Sint";
        case WGPUTextureFormat_BGRA8Unorm:
            return "WGPUTextureFormat_BGRA8Unorm";
        case WGPUTextureFormat_BGRA8UnormSrgb:
            return "WGPUTextureFormat_BGRA8UnormSrgb";
        case WGPUTextureFormat_RGB10A2Uint:
            return "WGPUTextureFormat_RGB10A2Uint";
        case WGPUTextureFormat_RGB10A2Unorm:
            return "WGPUTextureFormat_RGB10A2Unorm";
        case WGPUTextureFormat_RG11B10Ufloat:
            return "WGPUTextureFormat_RG11B10Ufloat";
        case WGPUTextureFormat_RGB9E5Ufloat:
            return "WGPUTextureFormat_RGB9E5Ufloat";
        case WGPUTextureFormat_RG32Float:
            return "WGPUTextureFormat_RG32Float";
        case WGPUTextureFormat_RG32Uint:
            return "WGPUTextureFormat_RG32Uint";
        case WGPUTextureFormat_RG32Sint:
            return "WGPUTextureFormat_RG32Sint";
        case WGPUTextureFormat_RGBA16Unorm:
            return "WGPUTextureFormat_RGBA16Unorm";
        case WGPUTextureFormat_RGBA16Snorm:
            return "WGPUTextureFormat_RGBA16Snorm";
        case WGPUTextureFormat_RGBA16Uint:
            return "WGPUTextureFormat_RGBA16Uint";
        case WGPUTextureFormat_RGBA16Sint:
            return "WGPUTextureFormat_RGBA16Sint";
        case WGPUTextureFormat_RGBA16Float:
            return "WGPUTextureFormat_RGBA16Float";
        case WGPUTextureFormat_RGBA32Float:
            return "WGPUTextureFormat_RGBA32Float";
        case WGPUTextureFormat_RGBA32Uint:
            return "WGPUTextureFormat_RGBA32Uint";
        case WGPUTextureFormat_RGBA32Sint:
            return "WGPUTextureFormat_RGBA32Sint";
        case WGPUTextureFormat_Stencil8:
            return "WGPUTextureFormat_Stencil8";
        case WGPUTextureFormat_Depth16Unorm:
            return "WGPUTextureFormat_Depth16Unorm";
        case WGPUTextureFormat_Depth24Plus:
            return "WGPUTextureFormat_Depth24Plus";
        case WGPUTextureFormat_Depth24PlusStencil8:
            return "WGPUTextureFormat_Depth24PlusStencil8";
        case WGPUTextureFormat_Depth32Float:
            return "WGPUTextureFormat_Depth32Float";
        case WGPUTextureFormat_Depth32FloatStencil8:
            return "WGPUTextureFormat_Depth32FloatStencil8";
        case WGPUTextureFormat_BC1RGBAUnorm:
            return "WGPUTextureFormat_BC1RGBAUnorm";
        case WGPUTextureFormat_BC1RGBAUnormSrgb:
            return "WGPUTextureFormat_BC1RGBAUnormSrgb";
        case WGPUTextureFormat_BC2RGBAUnorm:
            return "WGPUTextureFormat_BC2RGBAUnorm";
        case WGPUTextureFormat_BC2RGBAUnormSrgb:
            return "WGPUTextureFormat_BC2RGBAUnormSrgb";
        case WGPUTextureFormat_BC3RGBAUnorm:
            return "WGPUTextureFormat_BC3RGBAUnorm";
        case WGPUTextureFormat_BC3RGBAUnormSrgb:
            return "WGPUTextureFormat_BC3RGBAUnormSrgb";
        case WGPUTextureFormat_BC4RUnorm:
            return "WGPUTextureFormat_BC4RUnorm";
        case WGPUTextureFormat_BC4RSnorm:
            return "WGPUTextureFormat_BC4RSnorm";
        case WGPUTextureFormat_BC5RGUnorm:
            return "WGPUTextureFormat_BC5RGUnorm";
        case WGPUTextureFormat_BC5RGSnorm:
            return "WGPUTextureFormat_BC5RGSnorm";
        case WGPUTextureFormat_BC6HRGBUfloat:
            return "WGPUTextureFormat_BC6HRGBUfloat";
        case WGPUTextureFormat_BC6HRGBFloat:
            return "WGPUTextureFormat_BC6HRGBFloat";
        case WGPUTextureFormat_BC7RGBAUnorm:
            return "WGPUTextureFormat_BC7RGBAUnorm";
        case WGPUTextureFormat_BC7RGBAUnormSrgb:
            return "WGPUTextureFormat_BC7RGBAUnormSrgb";
        case WGPUTextureFormat_ETC2RGB8Unorm:
            return "WGPUTextureFormat_ETC2RGB8Unorm";
        case WGPUTextureFormat_ETC2RGB8UnormSrgb:
            return "WGPUTextureFormat_ETC2RGB8UnormSrgb";
        case WGPUTextureFormat_ETC2RGB8A1Unorm:
            return "WGPUTextureFormat_ETC2RGB8A1Unorm";
        case WGPUTextureFormat_ETC2RGB8A1UnormSrgb:
            return "WGPUTextureFormat_ETC2RGB8A1UnormSrgb";
        case WGPUTextureFormat_ETC2RGBA8Unorm:
            return "WGPUTextureFormat_ETC2RGBA8Unorm";
        case WGPUTextureFormat_ETC2RGBA8UnormSrgb:
            return "WGPUTextureFormat_ETC2RGBA8UnormSrgb";
        case WGPUTextureFormat_EACR11Unorm:
            return "WGPUTextureFormat_EACR11Unorm";
        case WGPUTextureFormat_EACR11Snorm:
            return "WGPUTextureFormat_EACR11Snorm";
        case WGPUTextureFormat_EACRG11Unorm:
            return "WGPUTextureFormat_EACRG11Unorm";
        case WGPUTextureFormat_EACRG11Snorm:
            return "WGPUTextureFormat_EACRG11Snorm";
        case WGPUTextureFormat_ASTC4x4Unorm:
            return "WGPUTextureFormat_ASTC4x4Unorm";
        case WGPUTextureFormat_ASTC4x4UnormSrgb:
            return "WGPUTextureFormat_ASTC4x4UnormSrgb";
        case WGPUTextureFormat_ASTC5x4Unorm:
            return "WGPUTextureFormat_ASTC5x4Unorm";
        case WGPUTextureFormat_ASTC5x4UnormSrgb:
            return "WGPUTextureFormat_ASTC5x4UnormSrgb";
        case WGPUTextureFormat_ASTC5x5Unorm:
            return "WGPUTextureFormat_ASTC5x5Unorm";
        case WGPUTextureFormat_ASTC5x5UnormSrgb:
            return "WGPUTextureFormat_ASTC5x5UnormSrgb";
        case WGPUTextureFormat_ASTC6x5Unorm:
            return "WGPUTextureFormat_ASTC6x5Unorm";
        case WGPUTextureFormat_ASTC6x5UnormSrgb:
            return "WGPUTextureFormat_ASTC6x5UnormSrgb";
        case WGPUTextureFormat_ASTC6x6Unorm:
            return "WGPUTextureFormat_ASTC6x6Unorm";
        case WGPUTextureFormat_ASTC6x6UnormSrgb:
            return "WGPUTextureFormat_ASTC6x6UnormSrgb";
        case WGPUTextureFormat_ASTC8x5Unorm:
            return "WGPUTextureFormat_ASTC8x5Unorm";
        case WGPUTextureFormat_ASTC8x5UnormSrgb:
            return "WGPUTextureFormat_ASTC8x5UnormSrgb";
        case WGPUTextureFormat_ASTC8x6Unorm:
            return "WGPUTextureFormat_ASTC8x6Unorm";
        case WGPUTextureFormat_ASTC8x6UnormSrgb:
            return "WGPUTextureFormat_ASTC8x6UnormSrgb";
        case WGPUTextureFormat_ASTC8x8Unorm:
            return "WGPUTextureFormat_ASTC8x8Unorm";
        case WGPUTextureFormat_ASTC8x8UnormSrgb:
            return "WGPUTextureFormat_ASTC8x8UnormSrgb";
        case WGPUTextureFormat_ASTC10x5Unorm:
            return "WGPUTextureFormat_ASTC10x5Unorm";
        case WGPUTextureFormat_ASTC10x5UnormSrgb:
            return "WGPUTextureFormat_ASTC10x5UnormSrgb";
        case WGPUTextureFormat_ASTC10x6Unorm:
            return "WGPUTextureFormat_ASTC10x6Unorm";
        case WGPUTextureFormat_ASTC10x6UnormSrgb:
            return "WGPUTextureFormat_ASTC10x6UnormSrgb";
        case WGPUTextureFormat_ASTC10x8Unorm:
            return "WGPUTextureFormat_ASTC10x8Unorm";
        case WGPUTextureFormat_ASTC10x8UnormSrgb:
            return "WGPUTextureFormat_ASTC10x8UnormSrgb";
        case WGPUTextureFormat_ASTC10x10Unorm:
            return "WGPUTextureFormat_ASTC10x10Unorm";
        case WGPUTextureFormat_ASTC10x10UnormSrgb:
            return "WGPUTextureFormat_ASTC10x10UnormSrgb";
        case WGPUTextureFormat_ASTC12x10Unorm:
            return "WGPUTextureFormat_ASTC12x10Unorm";
        case WGPUTextureFormat_ASTC12x10UnormSrgb:
            return "WGPUTextureFormat_ASTC12x10UnormSrgb";
        case WGPUTextureFormat_ASTC12x12Unorm:
            return "WGPUTextureFormat_ASTC12x12Unorm";
        case WGPUTextureFormat_ASTC12x12UnormSrgb:
            return "WGPUTextureFormat_ASTC12x12UnormSrgb";
        case WGPUTextureFormat_R8BG8Biplanar420Unorm:
            return "WGPUTextureFormat_R8BG8Biplanar420Unorm";
        case WGPUTextureFormat_R10X6BG10X6Biplanar420Unorm:
            return "WGPUTextureFormat_R10X6BG10X6Biplanar420Unorm";
        case WGPUTextureFormat_R8BG8A8Triplanar420Unorm:
            return "WGPUTextureFormat_R8BG8A8Triplanar420Unorm";
        case WGPUTextureFormat_R8BG8Biplanar422Unorm:
            return "WGPUTextureFormat_R8BG8Biplanar422Unorm";
        case WGPUTextureFormat_R8BG8Biplanar444Unorm:
            return "WGPUTextureFormat_R8BG8Biplanar444Unorm";
        case WGPUTextureFormat_R10X6BG10X6Biplanar422Unorm:
            return "WGPUTextureFormat_R10X6BG10X6Biplanar422Unorm";
        case WGPUTextureFormat_R10X6BG10X6Biplanar444Unorm:
            return "WGPUTextureFormat_R10X6BG10X6Biplanar444Unorm";
        case WGPUTextureFormat_External:
            return "WGPUTextureFormat_External";
        case WGPUTextureFormat_Force32:
            return "WGPUTextureFormat_Force32";
    }
    return "Unknown WGPUTextureFormat";
}

} // namespace ltb::wgpu
